name: Testing

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Switch to version 1.47
        run: rustup default 1.47.0
      - name: Add clippy
        run: rustup component add clippy
      - name: Build
        run: cargo build
      - name: Run clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: target
          key: Test dependencies
